(() => {
  const $ = id => document.getElementById(id);
  const rounds = [
    {name:'GIRAFFE TRAIL', title:'Giraffe Trail', code:'FIELD NOTE 01', sketch:'giraffe', stamp:'GIRAFFE TRACK\nSTAMP', seconds:120, bank:['avoid','predator','therefore','surface','journey','average'], answers:['therefore','avoid','predator'], hints:['Look for a cause-and-effect clue.','Think about stopping something from happening.','Think about an animal that hunts other animals.'], paragraphs:[
      ['Sleeping can be dangerous for animals in the wild. Giraffes, for example, do not usually sleep for very long. Because of their large bodies and long legs, they cannot get up quickly when danger comes. ',0,', they often take only short naps. They may stand quietly with their heads low, ready to move if they hear a strange sound.'],
      ['Sea otters face a different problem. They often sleep while floating on the water. To ',1,' drifting away from the group, they may hold on to one another. Staying together also makes them safer when a ',2,' is nearby.'] ]},
    {name:'OCEAN WATCH', title:'Ocean Watch', code:'FIELD NOTE 02', sketch:'ocean', stamp:'OCEAN WATCH\nSTAMP', seconds:120, bank:['awake','surface','look out for','impressive','distant','float','average'], answers:['awake','surface','look out for','impressive'], hints:['You need an adjective here.','Think about the top of the water.','Think about watching for danger.','You need an adjective to describe the example.'], paragraphs:[
      ['Dolphins have developed an unusual way to rest in the ocean. When they sleep, part of their brain remains ',0,'. This allows them to continue swimming and return to the water’s ',1,' when they need to breathe.'],
      ['Even while resting, dolphins must ',2,' sharks and other dangers around them. They also sleep near other dolphins, so the group can stay close and move safely through the sea. Their special sleeping habit may seem strange to humans, but it is an ',3,' example of how animals adapt to life in the wild. This teamwork gives them a better chance to notice trouble early.'] ]},
    {name:'SURVIVAL FLIGHT', title:'Survival Flight', code:'FIELD NOTE 03', sketch:'flight', stamp:'SWIFT FLIGHT\nSTAMP', seconds:120, bank:['journey','flight','variety','surviving','average','breath','creature','distant'], answers:['journey','flight','variety','surviving'], hints:['Think about a long trip.','Think about moving through the air.','Think about many different kinds.','Look at the phrase “method of + V-ing.”'], paragraphs:[
      ['Some migratory birds spend a surprisingly long time in the air during their ',0,'. Instead of landing every night, some can rest for short periods while they are still in ',1,'. Staying in the sky may help them avoid dangerous animals on the ground.'],
      ['These sleeping habits show the great ',2,' of ways animals deal with danger. Every species has developed its own method of ',3,' in the wild. For these birds, sleep is not simply rest; it is part of a careful plan for safety. What seems unusual to us may actually be an important life-saving skill.'] ]}
  ];
  let state={round:0,placed:[],attempts:[],selected:null,timer:null,left:0,started:false};
  const say=(message,ms=1600)=>{const t=$('toast');t.textContent=message;t.classList.add('show');clearTimeout(say.id);say.id=setTimeout(()=>t.classList.remove('show'),ms)};
  function showOverlay(title,text,label,fn,stamp='SAFARI\nNOTES'){ $('overlayTitle').textContent=title;$('overlayText').textContent=text;$('overlayButton').textContent=label;$('modalStamp').textContent=stamp;$('overlayButton').onclick=()=>{$('overlay').classList.add('hidden');fn()};$('overlay').classList.remove('hidden'); }
  function render(){const r=rounds[state.round];clearInterval(state.timer);state.placed=Array(r.answers.length).fill(null);state.attempts=Array(r.answers.length).fill(0);state.selected=null;state.started=false;$('roundNo').textContent=`ROUND ${state.round+1} / 3`;$('roundName').textContent=r.name;$('articleTitle').textContent=r.title;$('pageCode').textContent=r.code;$('pageStamp').textContent='WILDLIFE OBSERVATION';$('progress').textContent=`NOTES : ${state.round} / 3`;$('roundSketch').className=`round-sketch ${r.sketch}`;$('hintBox').textContent='Choose a card, then choose a blank.';$('hintBox').className='hint-box';renderReading();renderBank();updateCheck();updateTime();}
  function renderReading(){const r=rounds[state.round],box=$('reading');box.innerHTML='';r.paragraphs.forEach(parts=>{const p=document.createElement('p');parts.forEach(part=>{if(typeof part==='number'){const b=document.createElement('button');b.type='button';b.className='blank empty';b.dataset.slot=part;b.setAttribute('aria-label',`第 ${part+1} 個空格`);b.onclick=()=>placeSelected(part);p.append(b)}else p.append(document.createTextNode(part));});box.append(p)});refreshSlots();}
  function renderBank(){const bank=$('wordBank');bank.innerHTML='';rounds[state.round].bank.forEach((word,i)=>{const b=document.createElement('button');b.type='button';b.className='word-card';b.dataset.word=word;b.style.setProperty('--tilt',`${(i%3-1)*1.2}deg`);b.textContent=word;b.onclick=()=>selectCard(word);b.draggable=true;b.addEventListener('dragstart',e=>{selectCard(word);e.dataTransfer.setData('text/plain',word)});b.addEventListener('pointerdown',startPointerDrag);bank.append(b)});document.querySelectorAll('.blank').forEach(b=>{b.addEventListener('dragover',e=>e.preventDefault());b.addEventListener('drop',e=>{e.preventDefault();placeWord(e.dataTransfer.getData('text/plain'),Number(b.dataset.slot))})});refreshCards();}
  function selectCard(word){if(!state.started)return;state.selected=state.selected===word?null:word;refreshCards();document.querySelectorAll('.blank').forEach(b=>b.classList.toggle('selected-slot',!!state.selected&&!b.classList.contains('correct')))}
  function placeSelected(slot){if(!state.started||!state.selected)return;placeWord(state.selected,slot)}
  function placeWord(word,slot){const r=rounds[state.round];if(!word||state.placed.includes(word)||document.querySelector(`.blank[data-slot="${slot}"]`).classList.contains('correct'))return;state.placed[slot]=word;state.selected=null;refreshSlots();refreshCards();updateCheck();}
  function refreshSlots(){document.querySelectorAll('.blank').forEach(b=>{const i=Number(b.dataset.slot),word=state.placed[i];b.textContent=word||'';b.classList.toggle('empty',!word);b.classList.remove('selected-slot');});}
  function refreshCards(){document.querySelectorAll('.word-card').forEach(b=>{b.classList.toggle('used',state.placed.includes(b.dataset.word));b.classList.toggle('selected',state.selected===b.dataset.word)});}
  function updateCheck(){$('checkButton').disabled=!state.started||state.placed.some(x=>!x)}
  function check(){const r=rounds[state.round];let all=true;state.placed.forEach((word,i)=>{const b=document.querySelector(`.blank[data-slot="${i}"]`);b.classList.remove('wrong');if(word===r.answers[i]){b.classList.add('correct');b.innerHTML=`${word}<span class="mini-stamp">✓</span>`}else{all=false;state.attempts[i]++;state.placed[i]=null;b.textContent='';b.classList.add('empty','wrong');setTimeout(()=>b.classList.remove('wrong'),800);const second=state.attempts[i]>=2;$('hintBox').textContent=second?r.hints[i]:'Not quite. Check the context!';$('hintBox').className=`hint-box ${second?'hinted':''}`;}});refreshCards();updateCheck();if(all){clearInterval(state.timer);setTimeout(()=>cleared(),420)}}
  function updateTime(){const el=$('timer');el.textContent=`TIME : ${String(Math.max(0,state.left)).padStart(2,'0')}`;el.classList.toggle('warning',state.left<=10);el.classList.toggle('pulse',state.left<=5&&state.left>0)}
  function startRound(){state.started=true;state.left=rounds[state.round].seconds;updateTime();updateCheck();state.timer=setInterval(()=>{state.left--;updateTime();if(state.left<=0){clearInterval(state.timer);state.started=false;updateCheck();showOverlay("TIME'S UP!",'This field note is not complete yet. Try this round again.','TRY THIS ROUND AGAIN',()=>{render();startRound()})}},1000)}
  function cleared(){const r=rounds[state.round];if(state.round<2){showOverlay('FIELD NOTE RECOVERED!',`You earned the ${r.stamp.replace('\n',' ')}.`, 'NEXT FIELD NOTE',()=>{state.round++;render();showOverlay('New Route Found!',`Page ${state.round+1} is ready. Read carefully before you choose.`, 'START ROUND',startRound,rounds[state.round].stamp)},r.stamp)}else{localStorage.setItem('safariExpedition.readingComplete','1');showOverlay('FIELD NOTES RESTORED!','You recovered all three pages of the expedition journal. You earned the SAFARI READING BADGE.','CONTINUE THE EXPEDITION',()=>{state.round=0;render();showOverlay('Safari Field Notes','Recover the missing words from each field journal page.','START ROUND',startRound)},'SAFARI READING\nBADGE')}}
  function startPointerDrag(e){if(e.pointerType==='mouse'||!state.started)return;const card=e.currentTarget,word=card.dataset.word,startX=e.clientX,startY=e.clientY;let ghost,moved=false;const move=ev=>{if(Math.hypot(ev.clientX-startX,ev.clientY-startY)<10)return;moved=true;if(!ghost){ghost=card.cloneNode(true);ghost.className='word-card drag-ghost';document.body.append(ghost)}ghost.style.left=`${ev.clientX}px`;ghost.style.top=`${ev.clientY}px`};const up=ev=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);if(ghost)ghost.remove();if(moved){const target=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('.blank');if(target)placeWord(word,Number(target.dataset.slot));}};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up,{once:true})}
  const baseRender=render;render=function(){baseRender();const art=document.querySelector('.art-image');const files=['giraffe-trail-journal.png','ocean-watch-journal.png','survival-flight-journal.png'];art.style.backgroundImage=`url('assets/images/${files[state.round]}')`};$('checkButton').onclick=check;render();showOverlay('Ready, Explorer?','Recover the missing words from each field journal page.','START ROUND',startRound);
})();
