(() => {
  const $ = id => document.getElementById(id);
  const roundMeta = [{name:'ASK THE RANGER',tag:'RANGER DESK',seconds:120},{name:'REPORT THE EVIDENCE',tag:'WILDLIFE RESEARCH BOARD',seconds:120},{name:'FINAL SAFARI REPORT',tag:'EXPEDITION COMMAND BOARD',seconds:150}];
  let state={round:1,index:0,order:[],bankOrder:[],wrong:0,tool:null,score:0,roundStartScore:0,timer:null,left:0,active:false};
  const qForRound = () => grammarQuestions.filter(q=>q.round===state.round);
  const question = () => qForRound()[state.index];
  const say=(text,ms=1500)=>{const t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(say.id);say.id=setTimeout(()=>t.classList.remove('show'),ms)};
  function overlay(title,text,label,fn,stamp='RANGER\nSTATION',metrics=''){ const button=$('overlayButton');$('overlayTitle').textContent=title;$('overlayText').textContent=text;button.textContent=label;button.onclick=()=>{$('overlay').classList.add('hidden');fn()};$('modalStamp').textContent=stamp;$('modalMetrics').innerHTML=metrics;$('modalActions').replaceChildren(button);$('overlay').classList.remove('hidden'); }
  function setTop(){const m=roundMeta[state.round-1];$('roundNo').textContent=`ROUND ${state.round} / 3`;$('roundName').textContent=m.name;$('boardTag').textContent=m.tag;$('progress').textContent=`MISSION ${state.index+1} / ${qForRound().length}`;$('score').textContent=`MISSION SCORE : ${state.score} / 1600`;}
  function shuffleOnce(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
  function choices(){const q=question();return [...q.chunks,...(q.distractors||[])]}
  function render(){clearInterval(state.timer);state.order=[];state.wrong=0;state.tool=null;state.active=false;setTop();const q=question();state.bankOrder=shuffleOnce(choices());$('situation').textContent=q.situation;$('original').textContent=q.originalSentence;$('originalLabel').textContent=q.grammarType==='indirect-question'?'DIRECT QUESTION':'ORIGINAL RECORD';$('hintBox').textContent='Study the situation, then build the sentence.';$('hintBox').className='hint-box';$('verified').classList.remove('show');$('missionContent').classList.toggle('hidden',!!q.correctTool);$('toolChooser').classList.toggle('hidden',!q.correctTool);$('toolFeedback').textContent='';document.querySelectorAll('[data-tool]').forEach(b=>{b.className='';b.disabled=false});renderChunks();}
  function renderChunks(){const bank=$('chunkBank'),zone=$('answerZone');bank.innerHTML='';zone.innerHTML='';state.bankOrder.forEach(token=>{if(!state.order.includes(token))bank.append(chunk(token))});if(!state.order.length){const p=document.createElement('span');p.className='zone-placeholder';p.textContent='Tap the strips in order, or drag them here.';zone.append(p)}else {state.order.forEach(token=>zone.append(chunk(token,true)));const note=document.createElement('span');note.className='zone-note';note.textContent='Tap a strip here to move it back.';zone.append(note)}}
  function chunk(token,inZone=false){const b=document.createElement('button');b.type='button';b.className='chunk';b.textContent=token;b.draggable=true;b.dataset.token=token;b.onclick=()=>{if(!state.active)return;if(inZone)state.order=state.order.filter(x=>x!==token);else state.order.push(token);renderChunks()};b.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',token));return b;}
  $('answerZone').addEventListener('dragover',e=>{e.preventDefault();$('answerZone').classList.add('dragover')});$('answerZone').addEventListener('dragleave',()=>$('answerZone').classList.remove('dragover'));$('answerZone').addEventListener('drop',e=>{e.preventDefault();$('answerZone').classList.remove('dragover');if(!state.active)return;const token=e.dataTransfer.getData('text/plain');if(token&&!state.order.includes(token)){state.order.push(token);renderChunks()}});
  $('clearButton').onclick=()=>{if(state.active){state.order=[];renderChunks()}};
  $('submitButton').onclick=submit;
  function selectTool(tool){const q=question();if(tool!==q.correctTool){state.wrong++;$('toolFeedback').textContent=state.wrong===1?'Think about the purpose: ask or report?':q.hint2;const b=document.querySelector(`[data-tool="${tool}"]`);b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),500);return}state.tool=tool;document.querySelectorAll('[data-tool]').forEach(b=>{b.classList.toggle('selected',b.dataset.tool===tool);b.disabled=true});$('toolFeedback').textContent=tool==='ask'?'ASK tool selected. Now arrange the question.':'REPORT tool selected. Now arrange the report.';$('missionContent').classList.remove('hidden');state.active=true;}
  document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>selectTool(b.dataset.tool));
  function submit(){if(!state.active)return;if(state.order.length!==question().correctOrder.length){$('hintBox').textContent='Use only the strips needed for the sentence.';$('hintBox').className='hint-box hint';return}if(state.order.join('|')===question().correctOrder.join('|')){correct();return}state.wrong++;const q=question();$('missionContent').classList.add('shake');setTimeout(()=>$('missionContent').classList.remove('shake'),560);$('hintBox').textContent=state.wrong===1?q.hint1:state.wrong===2?q.hint2:q.hint3;$('hintBox').className='hint-box hint';}
  function earned(){return state.wrong===0?100:state.wrong===1?80:state.wrong===2?60:40}
  function correct(){clearInterval(state.timer);state.score+=earned();setTop();$('missionContent').classList.add('correct-zone');$('verified').classList.add('show');say(`REPORT VERIFIED! +${earned()} points`);setTimeout(next,950)}
  function next(){$('missionContent').classList.remove('correct-zone');if(state.index<qForRound().length-1){state.index++;render();startTimer();return}
    const roundPoints=qForRound().length*100;const roundScore=state.score-state.roundStartScore;const percent=Math.round(roundScore/roundPoints*100);clearInterval(state.timer);if(state.round<3){const title=state.round===1?'RANGER INTERVIEW CLEARED':'FIELD REPORT VERIFIED';const badge=state.round===1?'ASK BADGE':'REPORT BADGE';overlay(title,`You earned the ${badge}. Grammar Accuracy: ${percent}%.`,'NEXT ROUND',()=>{state.round++;state.index=0;state.roundStartScore=state.score;render();overlay('New Mission Ready',`${roundMeta[state.round-1].name} is ready.`, 'START ROUND',startTimer,roundMeta[state.round-1].tag.replaceAll(' ','\n'))},badge,`MISSION SCORE: ${roundScore} / ${roundPoints}`)}else finish(percent)}
  function finish(percent){localStorage.setItem('safariExpedition.grammarComplete','1');const badges='<div class="badges"><div class="badge">VOCABULARY<br>BADGE</div><div class="badge">READING<br>BADGE</div><div class="badge">GRAMMAR<br>RANGER BADGE</div></div>';overlay('EXPEDITION COMPLETE!','You completed the Safari English Expedition.','REPLAY GRAMMAR MISSION',reset,'FINAL\nEXPEDITION\nPASS',`${badges}<p>Final Grammar Accuracy: ${percent}%<br>Final Mission Score: ${state.score} / 1600</p>`);const results=document.createElement('button');results.type='button';results.className='return-button';results.textContent='VIEW EXPEDITION RESULTS';results.onclick=()=>say(`Final Mission Score: ${state.score} / 1600`);const returnMap=document.createElement('a');returnMap.href='../大冒險地圖/index.html';returnMap.className='return-button';returnMap.textContent='← BACK TO SAFARI MAP';$('modalActions').prepend(results);$('modalActions').append(returnMap)}
  function updateTime(){const el=$('timer');el.textContent=`TIME : ${String(Math.max(0,state.left)).padStart(2,'0')}`;el.classList.toggle('warning',state.left<=10);el.classList.toggle('pulse',state.left<=5&&state.left>0)}
  function startTimer(){state.active=true;state.left=roundMeta[state.round-1].seconds;updateTime();state.timer=setInterval(()=>{state.left--;updateTime();if(state.left<=0){clearInterval(state.timer);state.active=false;overlay("TIME'S UP!",'This ranger mission is not complete yet. Try this round again.','TRY THIS ROUND AGAIN',()=>{state.score=state.roundStartScore;state.index=0;render();startTimer()},'TIME\'S\nUP!')}},1000)}
  function reset(){clearInterval(state.timer);state={round:1,index:0,order:[],bankOrder:[],wrong:0,tool:null,score:0,roundStartScore:0,timer:null,left:0,active:false};render();overlay('Welcome, Explorer!','Complete three Ranger Grammar Missions to earn your FINAL EXPEDITION PASS.','START MISSION',startTimer)}
  $('compassButton').onclick=()=>{const open=$('compassPanel').classList.toggle('hidden');$('compassButton').setAttribute('aria-expanded',String(!open));$('compassButton').querySelector('span').textContent=open?'⌄':'⌃'};
  reset();
})();
