/* Teacher-editable grammar question bank. Each chunk has one intended place in the sentence. */
const grammarQuestions = [
 {id:'ask-1',round:1,situation:'You want to ask the ranger about giraffes.',originalSentence:'Where do giraffes sleep?',grammarType:'indirect-question',chunks:['Do you know','where','giraffes','sleep'],correctOrder:['Do you know','where','giraffes','sleep'],hint1:'Check the word order.',hint2:'ASK FORMULA: Starter + wh-word + subject + verb',hint3:'Start with the ranger-question starter, then put “where” before the subject.'},
 {id:'ask-2',round:1,situation:'You are curious about sea otters.',originalSentence:'Why do sea otters hold hands?',grammarType:'indirect-question',chunks:['Can you tell me','why','sea otters','hold hands'],correctOrder:['Can you tell me','why','sea otters','hold hands'],hint1:'Check the word order.',hint2:'ASK FORMULA: Starter + wh-word + subject + verb',hint3:'After “why,” place the animal group before its action.'},
 {id:'ask-3',round:1,situation:'You want to learn about dolphin sleep.',originalSentence:'How do dolphins sleep?',grammarType:'indirect-question',chunks:['I wonder','how','dolphins','sleep'],correctOrder:['I wonder','how','dolphins','sleep'],hint1:'No question word order after “how.”',hint2:'ASK FORMULA: Starter + wh-word + subject + verb',hint3:'Put “dolphins” immediately after “how.”'},
 {id:'ask-4',round:1,situation:'You want to know about Alpine swifts.',originalSentence:'When do Alpine swifts rest?',grammarType:'indirect-question',chunks:['Do you know','when','Alpine swifts','rest'],correctOrder:['Do you know','when','Alpine swifts','rest'],hint1:'Check the word order.',hint2:'ASK FORMULA: Starter + wh-word + subject + verb',hint3:'The time word comes before “Alpine swifts.”'},
 {id:'ask-5',round:1,situation:'You want to understand animal survival.',originalSentence:'Why are these sleeping habits important?',grammarType:'indirect-question',chunks:['Can you explain','why','these sleeping habits','are important'],correctOrder:['Can you explain','why','these sleeping habits','are important'],hint1:'Check the word order.',hint2:'ASK FORMULA: Starter + wh-word + subject + verb',hint3:'Put the subject before “are important.”'},
 {id:'report-1',round:2,situation:'A ranger needs a formal observation report.',originalSentence:'Scientists observed the giraffes at night.',grammarType:'passive-voice',chunks:['The giraffes','were','observed','at night'],distractors:['was','are','observing'],correctOrder:['The giraffes','were','observed','at night'],hint1:'Check the verb form.',hint2:'REPORT FORMULA: subject + be + past participle',hint3:'The plural subject needs “were” + Vpp.'},
 {id:'report-2',round:2,situation:'A research record needs to name who did the action.',originalSentence:'Researchers recorded the dolphins’ brain activity.',grammarType:'passive-voice',chunks:['The dolphins’ brain activity','was','recorded','by researchers'],distractors:['were','is','recording'],correctOrder:['The dolphins’ brain activity','was','recorded','by researchers'],hint1:'Check the subject and be verb.',hint2:'“Brain activity” is singular: be + past participle',hint3:'Use “was” + “recorded,” not a V-ing form.'},
 {id:'report-3',round:2,situation:'A wildlife alert explains a possible danger.',originalSentence:'Wild animals may catch Alpine swifts if they land.',grammarType:'passive-voice',chunks:['Alpine swifts','may','be','caught','by wild animals','if they land'],distractors:['are','catch','catching'],correctOrder:['Alpine swifts','may','be','caught','by wild animals','if they land'],hint1:'Check the modal verb form.',hint2:'After a modal verb: may + be + p.p.',hint3:'After “may,” use “be” before the past participle “caught.”'},
 {id:'report-4',round:2,situation:'The station is writing a formal fact report.',originalSentence:'Scientists report that some giraffes sleep only thirty minutes a day.',grammarType:'passive-voice',chunks:['It','is','reported','that','some giraffes','sleep only thirty minutes a day'],distractors:['are','was','reporting'],correctOrder:['It','is','reported','that','some giraffes','sleep only thirty minutes a day'],hint1:'Use the formal reporting structure.',hint2:'It + be + p.p. + that-clause',hint3:'Singular “It” needs “is” + “reported.”'},
 {id:'report-5',round:2,situation:'The station is describing an ongoing worldwide study.',originalSentence:'Researchers study different sleeping habits around the world.',grammarType:'passive-voice',chunks:['Different sleeping habits','are','studied','around the world','by researchers'],distractors:['is','were','studying'],correctOrder:['Different sleeping habits','are','studied','around the world','by researchers'],hint1:'Check the verb form.',hint2:'REPORT FORMULA: subject + be + past participle',hint3:'The plural subject needs “are” + “studied.”'},
 {id:'final-1',round:3,situation:'You want to ask the ranger about sea otters.',originalSentence:'Why do sea otters hold hands?',grammarType:'indirect-question',correctTool:'ask',chunks:['Can you tell me','why','sea otters','hold hands'],correctOrder:['Can you tell me','why','sea otters','hold hands'],hint1:'Choose the tool that asks for information.',hint2:'ASK: Starter + wh-word + subject + verb',hint3:'Use “Can you tell me” to begin this question.'},
 {id:'final-2',round:3,situation:'Scientists found this fact about giraffes.',originalSentence:'Scientists report that some giraffes sleep only thirty minutes a day.',grammarType:'passive-voice',correctTool:'report',chunks:['It','is','reported','that','some giraffes','sleep only thirty minutes a day'],distractors:['are','was','reporting'],correctOrder:['It','is','reported','that','some giraffes','sleep only thirty minutes a day'],hint1:'Choose the tool that reports information.',hint2:'REPORT: It + be + p.p. + that-clause',hint3:'The formal report begins with “It” + “is” + “reported.”'},
 {id:'final-3',round:3,situation:'You want to know more about Alpine swifts.',originalSentence:'How long can Alpine swifts stay in the air?',grammarType:'indirect-question',correctTool:'ask',chunks:['Do you know','how long','Alpine swifts','can stay','in the air'],correctOrder:['Do you know','how long','Alpine swifts','can stay','in the air'],hint1:'Choose the tool that asks for information.',hint2:'ASK: Starter + wh-word + subject + verb',hint3:'“How long” comes before “Alpine swifts.”'},
 {id:'final-4',round:3,situation:'Describe what may happen if the birds land.',originalSentence:'Wild animals may catch them.',grammarType:'passive-voice',correctTool:'report',chunks:['They','may','be','caught','by wild animals'],distractors:['are','catch','catching'],correctOrder:['They','may','be','caught','by wild animals'],hint1:'Choose the tool that reports information.',hint2:'REPORT: modal + be + p.p.',hint3:'Put “may” + “be” + “caught” right after “They.”'},
 {id:'final-5',round:3,situation:'You want to understand animal survival strategies.',originalSentence:'How do different animals avoid danger?',grammarType:'indirect-question',correctTool:'ask',chunks:['I wonder','how','different animals','avoid danger'],correctOrder:['I wonder','how','different animals','avoid danger'],hint1:'Choose the tool that asks for information.',hint2:'ASK: Starter + wh-word + subject + verb',hint3:'After “how,” place “different animals.”'},
 {id:'final-6',round:3,situation:'You are writing the final wildlife report.',originalSentence:'Researchers have observed many unusual sleeping habits.',grammarType:'passive-voice',correctTool:'report',chunks:['Many unusual sleeping habits','have','been','observed','by researchers'],distractors:['has','were','observing'],correctOrder:['Many unusual sleeping habits','have','been','observed','by researchers'],hint1:'Choose the tool that reports information.',hint2:'REPORT: subject + have/has been + p.p.',hint3:'The plural subject needs “have” + “been” + “observed.”'}
];
